### ISSUE TITLE
Language files seem to indicate Spanish (Español / es) rather than English (en)

### ISSUE THREAD

**Issue by jameswomack** [conventional-changelog/conventionalcommits.org#10]
Paths like lang/es/index.md have usually referred to Español in my experience. Were these files intended to be placeholders for Spanish?

**Comment by bcoe** [comment]
@jameswomack yeah, I left this file as a placeholder indicating how we could eventually internationalize -- this is the file structure used by semver.org.

**Comment by jameswomack** [comment]
@bcoe got it
