### ISSUE TITLE
Shorthand for "BREAKING CHANGE:"

### ISSUE THREAD

**Issue by koddsson** [conventional-changelog/conventionalcommits.org#14]
Could we add a "BREAK:" shorthand for "BREAKING CHANGE:"? 

Reason being if I have a long component there's not a whole lot of space left to write a meaningful description for the CHANGELOG.

**Comment by koddsson** [comment]
It got pointed out to me on twitter that you put `BREAKING CHANGE:` in the footer to signify a major version.

**Comment by bcoe** [comment]
@koddsson 👍 I haven't actually played with the footer stanza on my OSS projects (although I'd noticed it discussed in the Angular docs, and made sure to faithfully define its behavior).

Out of curiosity, what tool are you using for CHANGELOG generation, did using the footer work well?

**Comment by koddsson** [comment]
I'm using `lerna` with the conventional-commits flag. It uses the [conventional-commits-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) utility under the hood.

I haven't made a breaking change commit yet, but I think it should work :)
