### ISSUE TITLE
Rename scope

### ISSUE THREAD

**Issue by goodmind** [conventional-changelog/conventionalcommits.org#22]
What commit message should be if I rename/move file into other scope?

**Comment by stevemao** [comment]
I think you can include 2 scopes EG:

```
refactor(scope1,scope2): rename
```

**Comment by goodmind** [comment]
Well, commitizen can't do something like this :(

**Comment by stevemao** [comment]
I think you just need to type `scope1,scope2` as your scope

**Comment by damianopetrungaro** [comment]
Closing this one due to inactivity :)
