### ISSUE TITLE
A playground page to try out the tools

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventionalcommits.org#3]
It would be good to build a client side tool to test/valid commit message. Users can select a preset in a dropdown list. They also need to input commit message(s). The commit messages could be colour highlighted by the parser. And a preview for the changelog that's generated based the commit messages.

**Comment by Tapppi** [comment]
I use [`husky`](https://github.com/typicode/husky) & [`validate-commit-msg`](https://github.com/kentcdodds/validate-commit-msg) for this, and they work pretty well.

**Comment by AndersDJohnson** [comment]
Also [`cz-cli`](https://github.com/commitizen/cz-cli), though I'm not sure that's what you mean here.

**Comment by stevemao** [comment]
Sorry I just meant to create a playground page with nice UI to try out these cool tools :)

**Comment by damianopetrungaro** [comment]
@stevemao  any news for this?

**Comment by stevemao** [comment]
@damianopetrungaro Unfortunately I'm not working on conventional-changelog anymore. But if anyone is interested please go ahead! 😄

**Comment by damianopetrungaro** [comment]
@stevemao let's close this for the moment in inactive since `Jul 1, 2017`
Feel free to open again if you want to.
