### ISSUE TITLE
conventionalcommit indicator

### ISSUE THREAD

**Issue by elypter** [conventional-changelog/conventionalcommits.org#34]
for machine readability and to differentiate normal commit messages from conventional commits i suggest that there should be one or more characters at the beginning of the line to indicate a conventional commit.

example:

$fix(gui):spelling error in settings wnidow

**Comment by stevemao** [comment]
Can you elaborate?

**Comment by elypter** [comment]
the point of a leading character is that it makes conventionalcommits easy to identify for tools and also for users. everyone who has seen one before immediately recognizes it and doesnt have to ponder if the commits just use a similar syntax by accident. it also helps to avoid conflicts if a commit of a project that doesnt support conventional commits just happens to have a commit with a valid syntax and if tools can identify conventional commit by a leading character it can also check for syntax errors. it also spreads the word if people visit a project with conventional commits and ask themselves what the meaning of the commit with same leading character mean and then got to the documentation or faq.

**Comment by stevemao** [comment]
Which tools are you talking about specifically? Have you tried https://github.com/conventional-changelog/conventional-commits-detector?

**Comment by elypter** [comment]
oh, i didnt know this tool. thanks

**Comment by stevemao** [comment]
It's Ok :)
