### ISSUE TITLE
Best practice handling overlapped types

### ISSUE THREAD

**Issue by doodlewind** [conventional-changelog/conventionalcommits.org#35]
By default the `feat` and `fix` types are orthogonal. If we define multi types, say, `test` and `doc`, how to decide the type when committing a change that: 

* Fixes a typo - `fix`
* The typo is in doc - `doc`
* The doc describes unit tests - `test`

Shall we allow multi types in commit message, or provide suggestion choosing types?

**Comment by stevemao** [comment]
say if you fix a typo of a var name or a comment in the code, it's `refactor`. Fix is for bug fixes. 

> The doc describes unit tests

If this has nothing to do with the tests themselves, it should just be `docs`

**Comment by doodlewind** [comment]
Thanks for your suggestion, while since such change may also belong to `chore`, the way choosing types seems to be a bit vague?

**Comment by stevemao** [comment]
`chore` was supported to be changing a `build` or `ci` script. Like changing your gulpfile should be a `chore`.

**Comment by damianopetrungaro** [comment]
@doodlewind  can we close this one or do you need other info?

**Comment by xianshenglu** [comment]
say if I fixed a bug in the build script, what's the type of that commit? `fix` or `build`?
