### ISSUE TITLE
Explain differences between Body and Footer content

### ISSUE THREAD

**Issue by damianopetrungaro** [conventional-changelog/conventionalcommits.org#37]
I would like to propose an explicit difference in Body and Footer section.
The footer should only contain info as BC, external links.

The body should only to explain what and why changed (more like a Product Manager perspective).

**Comment by stevemao** [comment]
> The footer should only contain info as BC, external links.

> The body should only to explain what and why changed (more like a Product Manager perspective).

That should be correct. PR welcome :)

**Comment by damianopetrungaro** [comment]
@stevemao  PR ready, please review it.
