### ISSUE TITLE
add section that showcases projects using conventionalcommits

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventionalcommits.org#4]
It would be good to showcase a few projects using conventional commits (yargs and istanbuljs are the ones I work on).

**Comment by bcoe** [comment]
Done., would be great to have folks (@stevemao, @Tapppi, @jameswomack, etc) submit a few of their links to good example projects using the convention.

**Comment by jameswomack** [comment]
@bcoe will do
