### ISSUE TITLE
Lead with an example on website

### ISSUE THREAD

**Issue by patcon** [conventional-changelog/conventionalcommits.org#40]
The website currently has nothing above the fold that helps someone quickly know how to confirm. The spec is really rad an specific, but I feel that when a [PR fails due to not conforming](https://github.com/chaijs/chaijs.github.io/pull/169), it would be a really great experience if I went straight to the website and felt like "ooooooh, I get it!" The the template-speak is helpful, a prominent example above the fold could really convey the MVP of what a conventional commit is :)

Thanks for your attention and consideration! If you have a favourite commit message that meets the spec and exercises it the a proper extent, pls do drop it, and I'll submit a PR 🎉

**Comment by damianopetrungaro** [comment]
Issue #21 is going to add some example.

**Comment by patcon** [comment]
Ah, sorry, skimmed issues, but forget to check open PR. Thanks @damianopetrungaro!
