### ISSUE TITLE
Discussion: Address verb tense in spec

### ISSUE THREAD

**Issue by patcon** [conventional-changelog/conventionalcommits.org#42]
Reticketed from: https://github.com/conventional-changelog/conventionalcommits.org/pull/21#discussion_r175686126

### Resources
- StakeOverflow: [Should I use past or present tense in git commit messages?](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages/8059167)

**Comment by damianopetrungaro** [comment]
I prefer using an imperative mood, as described in the linked article [in this slide](https://slides.com/damianopetrungaro/working-with-git#/0/12)

**Comment by patcon** [comment]
Ditto. Past tense makes for more sensible changelog creation automation imho, so I'd love to recco that

**Comment by damianopetrungaro** [comment]
Closing this one due to inactivity :)
