### ISSUE TITLE
Update translations to 1.0.0-beta.2

### ISSUE THREAD

**Issue by damianopetrungaro** [conventional-changelog/conventionalcommits.org#46]
Hey beautiful people! We are slowly moving forward, but we are doing it!

We bumped up the version to: 
### **1.0.0-beta.2**! 🎉 

We need to update the current translations and we need your help!
@Morishiri and @doodlewind  could you please help us? (or tag someone who may do it)
I will update the Italian translations cause I did it 😄 

Thank you for your contributions!

**Comment by damianopetrungaro** [comment]
- [ ]  Italian translation @damianopetrungaro
- [ ] Polish translation @Morishiri
- [ ] Chinese translation @doodlewind

**Comment by Morishiri** [comment]
@damianopetrungaro here it is :)

**Comment by damianopetrungaro** [comment]
@Morishiri wow! Super fast! Thank you!

**Comment by damianopetrungaro** [comment]
Italian merged too!
Missing only @doodlewind with Chinese 😄

**Comment by doodlewind** [comment]
@damianopetrungaro landed now :-)

**Comment by damianopetrungaro** [comment]
@doodlewind I added the auto-deploy on heroku, let's see if it's working :D
