### ISSUE TITLE
Why `docs` ? The `s` is too much, no ?

### ISSUE THREAD

**Issue by kosssi** [conventional-changelog/conventionalcommits.org#61]
I don't understand why only `docs` have `s`. Have you references/links ?

**Comment by damianopetrungaro** [comment]
Hey!
Thank you for the question @kosssi !
Actually, I don't know if there's a proper way in English to say that.

But if you're right we need to update the documentation for sure!
@bcoe you are an English native speaker, what do you think about it?

**Comment by kudos** [comment]
As a native speaker, I find `docs` to be the more natural shorthand.

In English, `doc` is short for document, both noun and verb. To help with disambiguation the shorthand `docs` is typically used for documentation. It doesn't imply a plurality of changes like it would do with `fix` or `feat`, it implies the area the change is affecting.

**Comment by damianopetrungaro** [comment]
🇮🇪He's from Ireland, he's right 😂 

@kosssi is it fine for you the explanation or you do think it may be still discussed?

**Comment by kosssi** [comment]
it's good explanation, thanks 👍

**Comment by damianopetrungaro** [comment]
Perfect!
Thank you @kosssi  for asking about your doubt and to @kudos  for explaining it to us 😄 

Closing this baby!
