### ISSUE TITLE
conventionalcommits badges

### ISSUE THREAD

**Issue by damianopetrungaro** [conventional-changelog/conventionalcommits.org#67]
Let's vote for some badges 😄 
Which one do you prefer?

![conventional-commits](https://img.shields.io/badge/conventional--commits-friendly-brightgreen.svg)
![conventional-commits](https://img.shields.io/badge/conventional--commits-supporter-brightgreen.svg)
![conventional-commits](https://img.shields.io/badge/conventional--commits-lover-brightgreen.svg)

Feel free to suggest new one using this -> ```![conventional-commits](https://img.shields.io/badge/conventional--commits-friendly-brightgreen.svg)```

**Comment by damianopetrungaro** [comment]
@conventional-changelog/conventional-chalengelog and @conventional-changelog/standard-version

**Comment by hbetts** [comment]
What problem(s) do these badges solve that isn't solved by the badge found at the bottom of - https://conventionalcommits.org/

**Comment by damianopetrungaro** [comment]
@hbetts  I've seen it 😂 
+1 for you 😄
