### ISSUE TITLE
Cool badges that are different from others—yet the same

### ISSUE THREAD

**Issue by jameswomack** [conventional-changelog/conventionalcommits.org#8]
![committer_badge](https://cloud.githubusercontent.com/assets/77849/24983269/ddd7a8cc-1f9a-11e7-9660-c5747106aa7c.png)

![conventional_badge](https://cloud.githubusercontent.com/assets/77849/24983271/ddd9a30c-1f9a-11e7-9f8c-50ce741c2f5f.png)

![version_badge](https://cloud.githubusercontent.com/assets/77849/24983270/ddd7f8fe-1f9a-11e7-81f5-212e7deb09b6.png)

[badge-source.zip](https://github.com/conventional-changelog/conventionalcommits.org/files/918111/badge-source.zip)

I want to have a badge or two that looks great with others, but holds personality so folks are proud to flaunt it. Having an image|icon in the badge is shown to hold more value in the attention economy as well. The resolution of the type is a bit off, but I've attached SVG and AI sources to rectify that as so desired.

**Comment by jameswomack** [comment]
The typeface used is Rift Soft. I can make another version with the type converted to outlines if needed.

**Comment by stevemao** [comment]
Man this is awesome 😃

**Comment by jameswomack** [comment]
@bcoe are you interested in having a version of one of these be finalized?

**Comment by bcoe** [comment]
@jameswomack I really love this 👍 make it so!

**Comment by jameswomack** [comment]
![image](https://cloud.githubusercontent.com/assets/77849/25106904/f7db3f56-2380-11e7-8093-eb0027ac42f5.png)

**Comment by damianopetrungaro** [comment]
@jameswomack  any update?

**Comment by damianopetrungaro** [comment]
Going to close this one and open a new one with other samples due to inactivity.
