### ISSUE TITLE
allow BREAKING CHANGE: with any verb.

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventionalcommits.org#9]
I think we should amend the specification to allow `BREAKING CHANGE:` with any commit type (right now we indicate that a BREAKING CHANGE should be a fix, or feat).

I'm finding as I drop Node 0.10/0.12 support on some libraries, I have `chore` commits that are breaking.

**Comment by stevemao** [comment]
Yes, see https://github.com/angular/angular/issues/5672
BTW, dropping Node 0.10/0.12 support should probably be a [`ci`](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type)

**Comment by jameswomack** [comment]
@bcoe I agree with this. I think one should try for `BREAKING CHANGE`s to be a `fix` or `feat`, but we need to accept that even dependency changes can be flagged as breaking when one takes stability & semver seriously.

**Comment by Tapppi** [comment]
@bcoe Agreed, we have lots of precedent both in our own projects and in the community. `standard-version` has a BREAKING chore too (node 0.10/0.12).

**Comment by jameswomack** [comment]
I'm closing based on #11 — feel free to re-open as needed.
